### ISSUE TITLE
Data Studio has encountered a system error.

### ISSUE THREAD

**Issue by goodosoft** [Tiggerito/GA4-Scripts#1]
System Error
Data Studio has encountered a system error.

Sorry, we encountered an error and were unable to complete your request.

Error ID: f8afd03e

**Comment by Tiggerito** [comment]
Unfortunately Data Studio is not very clear with its errors. Could you provide more details on what and how things are failing.

**Comment by goodosoft** [comment]
![image](https://user-images.githubusercontent.com/10493935/150938635-cc1245fa-0aa7-4d8b-96d7-a596e20efd7b.png)

**Comment by Tiggerito** [comment]
If you share the report with me (tony@websiteadvantage.com.au) I could take a look.

With those errors I'd first switch to edit mode and click on the erroring chart. To the right it lists the data used, maybe for some reason one of the variables is erroring or the formula in the data source is broken.

Sometimes changing the data range can fix things.

**Comment by goodosoft** [comment]
![image](https://user-images.githubusercontent.com/10493935/151118558-6cd4022d-48c3-4e04-93f4-c524ac14fed6.png)
change data range  does not working.
All variables   seems  normal.

**Comment by Tiggerito** [comment]
It's hard to debug without direct access. 

I presume the "see details" is of no use. 

One other potential issue is that sometimes when copying a data source it adds a field in twice. One works and the other does not. Have a look at the data source for duplicates. If so, rename one so you can identify which is being used in the report. Then try switching the field in the report to the other one.

**Comment by goodosoft** [comment]
I have shared the report with you.
Please take a look when you have time.
Thanks.

**Comment by Tiggerito** [comment]
The secondary sort on those tables were causing the issue, I just reset it to the same field and it worked.

There are other issues with the report. Filters have gone missing from the charts and their values are all lost. 

It may be worth trying to create it again, and look out for any errors as it is created.

I can't access the datasource so can't check if it is ok.

Data Studio is very flaky when it comes to trying to share reports with different datasources.
